# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 647)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_kaydet_hobiler = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kaydet_hobiler.setGeometry(QtCore.QRect(100, 290, 201, 81))
        self.btn_kaydet_hobiler.setObjectName("btn_kaydet_hobiler")
        self.lbl_sonuc_hobiler = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sonuc_hobiler.setGeometry(QtCore.QRect(100, 400, 211, 191))
        self.lbl_sonuc_hobiler.setText("")
        self.lbl_sonuc_hobiler.setObjectName("lbl_sonuc_hobiler")
        self.groupHobbies = QtWidgets.QGroupBox(self.centralwidget)
        self.groupHobbies.setGeometry(QtCore.QRect(100, 30, 211, 231))
        self.groupHobbies.setObjectName("groupHobbies")
        self.widget = QtWidgets.QWidget(self.groupHobbies)
        self.widget.setGeometry(QtCore.QRect(20, 50, 171, 131))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_cinema = QtWidgets.QCheckBox(self.widget)
        self.cb_cinema.setObjectName("cb_cinema")
        self.verticalLayout.addWidget(self.cb_cinema)
        self.cb_kitap = QtWidgets.QCheckBox(self.widget)
        self.cb_kitap.setObjectName("cb_kitap")
        self.verticalLayout.addWidget(self.cb_kitap)
        self.cb_spor = QtWidgets.QCheckBox(self.widget)
        self.cb_spor.setObjectName("cb_spor")
        self.verticalLayout.addWidget(self.cb_spor)
        self.groupClasses = QtWidgets.QGroupBox(self.centralwidget)
        self.groupClasses.setGeometry(QtCore.QRect(460, 20, 211, 231))
        self.groupClasses.setObjectName("groupClasses")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupClasses)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 50, 171, 131))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cb_Math = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_Math.setObjectName("cb_Math")
        self.verticalLayout_5.addWidget(self.cb_Math)
        self.cb_webdesign = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_webdesign.setObjectName("cb_webdesign")
        self.verticalLayout_5.addWidget(self.cb_webdesign)
        self.cb_programming = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_programming.setObjectName("cb_programming")
        self.verticalLayout_5.addWidget(self.cb_programming)
        self.btn_kaydet_dersler = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kaydet_dersler.setGeometry(QtCore.QRect(470, 290, 201, 81))
        self.btn_kaydet_dersler.setObjectName("btn_kaydet_dersler")
        self.lbl_sonuc_dersler = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sonuc_dersler.setGeometry(QtCore.QRect(460, 390, 211, 191))
        self.lbl_sonuc_dersler.setText("")
        self.lbl_sonuc_dersler.setObjectName("lbl_sonuc_dersler")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_kaydet_hobiler.setText(_translate("MainWindow", "Seçilenleri Kaydet"))
        self.groupHobbies.setTitle(_translate("MainWindow", "GroupBox"))
        self.cb_cinema.setText(_translate("MainWindow", "Sinema"))
        self.cb_kitap.setText(_translate("MainWindow", "Kitap okumak"))
        self.cb_spor.setText(_translate("MainWindow", "Spor"))
        self.groupClasses.setTitle(_translate("MainWindow", "GroupBox"))
        self.cb_Math.setText(_translate("MainWindow", "Matematik"))
        self.cb_webdesign.setText(_translate("MainWindow", "Web Tasarım"))
        self.cb_programming.setText(_translate("MainWindow", "Programlama"))
        self.btn_kaydet_dersler.setText(_translate("MainWindow", "Seçilenleri Kaydet"))
